services:
  web:
    build:
     context: .
     target: builder
    ports:
      - '8000:5000'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
